// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5dafa4pdv6DZ5wQioHVvSjHyx0hc-CA',
    appId: '1:960704958225:web:13559286543840eb39c6b0',
    messagingSenderId: '960704958225',
    projectId: 'akwatv-42392',
    authDomain: 'akwatv-42392.firebaseapp.com',
    storageBucket: 'akwatv-42392.appspot.com',
    measurementId: 'G-M0PZ2YKLQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zlnVFmSBuX9tuMtTbI9h5Umj_-raYPI',
    appId: '1:960704958225:android:0131f834cbd0db8539c6b0',
    messagingSenderId: '960704958225',
    projectId: 'akwatv-42392',
    storageBucket: 'akwatv-42392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbcoX05dfy7DAJDpV1q_Q3QPqyFJAGlmE',
    appId: '1:960704958225:ios:4c24b473731981fb39c6b0',
    messagingSenderId: '960704958225',
    projectId: 'akwatv-42392',
    storageBucket: 'akwatv-42392.appspot.com',
    iosClientId: '960704958225-4u1omsqb0ojs65b1offn12t2ejhn2047.apps.googleusercontent.com',
    iosBundleId: 'com.example.akwatv',
  );
}
