import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // ENGLISH LANGUAGE
        'en_US': {
          'logout': 'Logout',
          'logoutText': 'Sure you want to logout?',
          'login': 'Login',
          'register': 'Register',
          'registerText': 'Sign Up to start your free seven days trial',
          'agreeRegister': 'By creating an account you agree to our',
          'letStart': "Let's get started",
          'rememberMe': "Remember me",
          'forgotPassword': "Forgot Password?",
          'linkEmail':
              "Enter your email address linked with your Akwa-TV account",
          'verifyOTP': 'OTP Verification',
          'otpText': "Enter OTP sent to your Akwa-TV account",
          'welcome': 'Welcome back!',
          'continue': 'Continue',
          'name': 'Full Name',
          'enterName': 'Enter your full name',
          'phone': 'Phone number',
          'enterPhone': 'Enter your phone number',
          'email': 'Email',
          'enterEmail': 'Enter your email',
          'password': 'Password',
          'newPassword': 'New Password',
          'currentPassword': 'Current Password',
          'enterCurrentPassword': 'Enter your current password',
          'enterPassword': 'Enter your password',
          'confirmNewPassword': 'Confirm New Password',
          'newPasswordText': 'Enter New Password',
          'createPassword':
              "Create new password to access your Akwa-Tv account",
          'resetPassword': 'Reset Password',

          'passwordSecurityText':
              'Update  password to secure your Akwa-Tv account',
          'terms': 'terms',
          'and': 'and',
          'yes': 'Yes',
          'no': 'No',
          'conditions': 'conditions',
          'profile': 'Profile',
          'networkText': 'Check your Internet Connection',

          'editProfile': 'Edit Profile',
          'notifications': 'Notifications',
          'language': 'Language',
          'aboutUs': 'About Us',
          'changePicture': 'Tap to change your picture',
          'search': 'Search',
          'searchBy': 'search by movie title',
          'topSearched': 'Top Searched',
          'noMovieFetched': 'No Movie Fetched',

          //home navigation
          'akwaType': 'Akwa Amaka Originals',
          'settings': 'Settings',
          'subscription': 'Subscription',
          'account': 'Account',
          'help': 'Help',
          'helpCenter': "Help Center",
          'hereToHelp': "We're here to help!",
          'callUs': "Call us",
          'sendEmail': "Send an Email",
          'termsAndCondition': "Terms and Conditions",
          'callCenter': "Call Center",
          'emergencyCall': "Emergency Call Center",
          'hiLetsHelp': "Hi, let's help you today",
          'tapToCall': "Tap the number to call",
          'watchlist': "WatchList",

          // subscription strings
          'choosePlan': 'Choose Plan',
          'planText': 'Subscribe for a Plan to enjoy Akwa Amaka TV Shows',
          'agreePlan': 'By Subscribing to Akwa Amaka TV you agree to our',
          'payLater': 'Pay Later',
          'subscribe': 'Subscribe',
          'freeTrial': 'Your free trial begins now',
          'freeTrialEnd': 'Your free trial has ended',
          'trialExpire': 'Your Subscription plan will expire on',
          'trialExpireEnd': 'Your Subscription plan expired on',
          'congratulations': 'Welcome',
          'currentPlan': 'Current Plan',
          'planExpired': 'Subscription Plan Expired',
          'planExpiredText':
              'Your current subscription has expired and you are required to subscribe to continue enjoying Akwa Amaka Tv Shows',
          'active': 'Active',
          'expire': 'Expired',
          'upgradePlan': 'Upgrade Plan',
          'upgradePlanText':
              'Upgrade now and enjoy awesome features on Akwa Amaka TV',
          'upgradePlanText2': 'Stream and enjoy awesome Akwa Amaka Tv shows',
          'amountPaid': 'Amount Paid',
          'validity': 'Validity',
          'paymentHistory': 'Payment History',
          'paymentHistoryText': 'Your Subscription payment history',

          //movie Strings
          'action': 'Action',
        },

        //FRENCH LANGUAGE
        'fr': {
          'logout': 'Déconnexion',
          'logoutText': 'Vous voulez bien vous déconnecter?',
          'login': 'Login',
          'register': 'Registre',
          'registerText':
              'Inscrivez-vous pour commencer votre essai gratuit de sept jours',
          'agreeRegister': 'En créant un compte, vous acceptez nos',
          'letStart': "Commençons",
          'rememberMe': "Souviens-toi de moi",
          'forgotPassword': "Mot de passe oublié?",
          'linkEmail':
              "Entrez votre adresse e-mail liée à votre compte Akwa-TV",
          'verifyOTP': 'Vérification OTP',
          'otpText': "Entrez OTP envoyé à votre compte Akwa-TV",
          'welcome': 'Nous saluons le retour!',
          'continue': 'Continuer',
          'name': 'Nom et prénom',
          'enterName': 'Entrez votre nom complet',
          'phone': 'Numéro de téléphone',
          'enterPhone': 'Entrez votre numéro de téléphone',
          'email': 'Email',
          'enterEmail': 'Entrer votre Email',
          'password': 'Mot de passe',
          'newPassword': 'nouveau mot de passe',
          'currentPassword': 'Mot de passe actuel',
          'enterCurrentPassword': 'Entrer votre mot de passe actuel',
          'enterPassword': 'Entrez votre mot de passe',
          'confirmNewPassword': 'Confirmer le nouveau mot de passe',
          'newPasswordText': 'Entrez un nouveau mot de passe',
          'createPassword':
              "Créez un nouveau mot de passe pour accéder à votre compte Akwa-Tv",
          'resetPassword': 'Réinitialisation du mot de passe',
          'passwordSecurityText':
              'Mettre à jour le mot de passe pour sécuriser votre compte Akwa-Tv',
          'terms': 'termes',
          'and': 'et',
          'yes': 'Oui',
          'no': 'Non',
          'conditions': 'les conditions',
          'profile': 'Profil',
          'editProfile': 'Editer le profil',
          'notifications': 'Notifications',
          'language': 'Langue',
          'aboutUs': 'À propos de nous',
          'changePicture': 'Appuyez pour changer votre image',
          'search': 'Chercher',
          'searchBy': 'rechercher par titre de film',
          'topSearched': 'Les plus recherchés',
          'noMovieFetched': 'Aucun film récupéré',
          'networkText': 'Vérifiez votre connection internet',

          //home navigation
          'akwaType': 'Akwa Amaka Originaux',
          'settings': 'Réglages',
          'subscription': 'Abonnement',
          'account': 'Compte',
          'help': 'Aider',
          'helpCenter': "Centre d'aide",
          'hereToHelp': "Nous sommes là pour vous aider !",
          'callUs': "Appelez-nous",
          'sendEmail': "Envoyer un e-mail",
          'termsAndCondition': "Termes et conditions",
          'callCenter': "Centre d'appel",
          'emergencyCall': "Centre d'appels d'urgence",
          'hiLetsHelp': "Salut, nous allons vous aider aujourd'hui",
          'tapToCall': "Appuyez sur le numéro à appeler",
          'watchlist': "Liste de surveillance",

          // subscription strings
          'choosePlan': 'Choisissez un forfait',
          'planText':
              "Abonnez-vous à un plan pour profiter des émissions de télévision d'Akwa Amaka",
          'agreePlan': 'En vous abonnant à Akwa Amaka TV, vous acceptez nos',
          'payLater': 'Payer plus tard',
          'subscribe': "S'abonner",
          'freeTrial': 'Votre essai gratuit commence maintenant',
          'freeTrialEnd': 'Votre essai gratuit est terminé',
          'trialExpire': "Votre plan d'abonnement expirera le",
          'trialExpireEnd': "Votre plan d'abonnement a expiré le",
          'congratulations': 'Bienvenu',
          'currentPlan': 'Plan actuel',
          'planExpired': "Plan d'abonnement expiré",
          'planExpiredText':
              "Votre abonnement actuel a expiré et vous devez vous abonner pour continuer à profiter des émissions de télévision Akwa Amaka",
          'active': 'Actif',
          'expire': 'Expiré',
          'upgradePlan': 'Plan de mise à niveau',
          'upgradePlanText':
              'Mettez à niveau maintenant et profitez de fonctionnalités impressionnantes sur Akwa Amaka TV',
          'upgradePlanText2': 'Diffusez et profitez des superbes émissions de télévision Akwa Amaka',
          'amountPaid': 'Le montant payé',
          'validity': 'Validité',
          'paymentHistory': 'Historique de paiement',
          'paymentHistoryText': 'Historique de paiement de votre abonnement',

          //movie Strings
          'action': 'Action',
        }
      };
}
