name: akwatv
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  get_storage: ^2.0.3
  get_it:
  flutter_screenutil: ^5.3.1
  flutter_launcher_icons: ^0.9.1
  chewie: ^1.3.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  is_first_run: ^1.0.0
  url_launcher: ^6.0.18
  fluttertoast: ^8.0.9
  better_player: ^0.0.82
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/image/logo.png"
  image_path_android: "assets/image/logo.png"





flutter:


  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Bold.ttf
        - asset: assets/fonts/Sarabun-Medium.ttf
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Light.ttf
