name: akwatv
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  get_storage: ^2.0.3
  get_it:
  flutter_screenutil: ^5.3.1
  flutter_launcher_icons: ^0.9.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  is_first_run: ^1.0.0
  url_launcher: ^6.0.18
  fluttertoast: ^8.0.9
  #better_player: ^0.0.83
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pinput: ^2.2.11
  flutter_cache_manager: ^3.3.0
  firebase_messaging: ^12.0.1
  firebase_core: ^1.20.0
  flutter_local_notifications: ^9.7.0
 # cached_video_player: ^2.0.3
  chewie: ^1.3.4
  # flutter_paystack: ^1.0.5+1
  flutter_paystack_payment: ^0.1.2
  better_player: ^0.0.83
  device_information: ^0.0.4
  shared_preferences: ^2.0.15
  internet_connection_checker: ^0.0.1+4
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/image/logo.png"
  image_path_android: "assets/image/logo.png"





flutter:


  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Bold.ttf
        - asset: assets/fonts/Sarabun-Medium.ttf
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Light.ttf
